"""Backing the irreplaceable files up to the iCloud sync directory.

The list below is not invented: it is what `git status --ignored` reports in a
rime-ice checkout, minus derived artifacts, minus the two files Rime's own sync
task owns, minus machine identity. `installation.yaml` carries
`installation_id`; copying one machine's to another makes two installations
claim the same identity.

Restore is deliberately additive. Four devices share this directory, so a local
file whose content the vault does not know about is a conflict, not something
to overwrite.
"""
from __future__ import annotations

import json
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Sequence

from .paths import sha256_file  # re-exported: this module's callers use it too

VAULTED_FILES = (
    "private/custom.dict.yaml",
    # The pristine Sogou export, kept because `clean` overwrites the live file
    # and nothing can regenerate this one.
    "private/custom.dict.yaml.raw",
    "private/dict.json",
    # Describes the shared *result* of cleaning -- whether the lexicon has
    # been cleaned and the sha256 of the pristine `.raw` it was cleaned from
    # (raw_sha256) -- so a second machine can tell what it is holding instead
    # of guessing from a `restore` that has not yet pulled `.raw` down. This is
    # NOT the same kind of stamp as `.copilot_build_stamp.json`
    # (freshness.STAMP_NAME), which stays machine-local on purpose: that one
    # describes a locally built database, derived fresh on every machine. Do
    # not "tidy" this one away into the machine-local category -- see
    # cmd_clean's C1 guard, which depends on every machine seeing the same
    # stamp.
    "private/.copilot_clean_stamp.json",
    "private.dict.yaml",
    # Generated by `rime-copilot personal`, and vaulted despite being derived
    # -- the same exception rime40m-q8.gguf takes, on a stronger argument.
    # private.dict.yaml (above) names it in import_tables, and a missing
    # import table does not degrade: get_dict_files_from_settings
    # (dict_compiler.cc:47-62) returns false on the first path that does not
    # exist, failing the whole dictionary build. The two files are only valid
    # as a pair, and that -- not the possibility of regenerating -- is what
    # earns the exception. The corpus does travel (iCloud, symlinked into
    # ~/.local/share/rime-corpus), but a machine whose symlinks are not set up
    # or whose iCloud has not finished downloading has none, and would rebuild
    # from custom.dict.yaml alone and report success. cmd_personal guards that
    # case; vaulting the file means restore does not depend on the guard.
    "private/personal.dict.yaml",
    # The neural re-ranking model. A derived artifact, and a large one, so it
    # sits oddly beside the rest of this list -- but deriving it again costs
    # ~14 hours of training and a 14GB corpus that is not distributed, and the
    # alternative is scp-ing 42MB to every machine by hand. Vaulting it makes
    # a second machine's `restore` enough.
    #
    # Named explicitly, so a retrain under a different filename does NOT
    # travel until this list is updated. That is the safe direction: the
    # second machine's `rime-copilot status` reports `model: missing` and
    # names the file the schema asked for, rather than silently running an
    # older model that happens to still be there.
    "private/rime40m-q8.gguf",
    # The 2026-08-22 retrain. Both names are carried on purpose: the schema
    # patch and the model both travel by vault, but a machine can restore
    # them in either order, and a schema naming a file the vault does not
    # hold is a silent fallback to the db path. Drop the old entry only
    # once every machine reports the new one in `status`.
    "private/rime40m-v2-q8.gguf",
    "default.custom.yaml",
    "double_pinyin_flypy.custom.yaml",
    "squirrel.custom.yaml",
    "custom_phrase_double.txt",
)

MANIFEST_NAME = "manifest.json"
FILES_DIR = "files"


@dataclass(frozen=True)
class Record:
    sha256: str
    size: int
    backed_up_at: str
    machine: str


@dataclass(frozen=True)
class Action:
    rel: str
    kind: str
    detail: str = ""


def safe_join(root: Path, rel: str) -> Path:
    """Join `rel` under `root`, refusing anything that escapes it.

    Two independent checks, because neither subsumes the other:

    - A literal `..` component is refused outright. `a/../../root/b` resolves
      back under `root` by coincidence of naming, so the containment check
      below would accept it, but it traverses outside on the way.
    - Containment is then verified against the *resolved* path, because a
      `rel` with no `..` at all still escapes if a component on disk is a
      symlink. Four devices share the vault, so a symlink planted there by
      any of them is a realistic way to redirect a write.

    This is a check, not a lock: a symlink planted between this call and the
    write would still win. Closing that needs O_NOFOLLOW-style handling and is
    out of scope here.
    """
    relpath = Path(rel)
    if relpath.is_absolute():
        raise ValueError(f"absolute path not allowed in the vault list: {rel}")
    if ".." in relpath.parts:
        raise ValueError(f"parent traversal not allowed in the vault list: {rel}")
    anchor = root.resolve()
    candidate = (root / rel).resolve()
    if anchor != candidate and anchor not in candidate.parents:
        raise ValueError(f"path escapes {anchor}: {rel}")
    return root / rel


def read_manifest(vault: Path) -> dict[str, Record]:
    path = vault / MANIFEST_NAME
    if not path.is_file():
        return {}
    raw = json.loads(path.read_text(encoding="utf-8"))
    return {rel: Record(**fields) for rel, fields in raw.get("files", {}).items()}


def write_manifest(vault: Path, records: dict[str, Record]) -> None:
    vault.mkdir(parents=True, exist_ok=True)
    payload = {"version": 1, "files": {rel: asdict(r) for rel, r in sorted(records.items())}}
    path = vault / MANIFEST_NAME
    temporary = path.with_suffix(".json.new")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
                         encoding="utf-8")
    temporary.replace(path)


def plan_restore(rime_dir: Path, vault: Path, *, force: bool = False) -> list[Action]:
    actions = []
    for rel in VAULTED_FILES:
        stored = safe_join(vault / FILES_DIR, rel)
        local = safe_join(rime_dir, rel)
        if not stored.is_file():
            actions.append(Action(rel, "missing-in-vault"))
        elif not local.exists():
            actions.append(Action(rel, "restore"))
        elif sha256_file(local) == sha256_file(stored):
            actions.append(Action(rel, "identical"))
        elif force:
            actions.append(Action(rel, "restore", "forced over local changes"))
        else:
            actions.append(Action(rel, "conflict", "local content is not in the vault"))
    return actions


def apply_restore(rime_dir: Path, vault: Path, actions: Sequence[Action]) -> None:
    for action in actions:
        if action.kind != "restore":
            continue
        stored = safe_join(vault / FILES_DIR, action.rel)
        local = safe_join(rime_dir, action.rel)
        local.parent.mkdir(parents=True, exist_ok=True)
        temporary = local.with_name(local.name + ".new")
        shutil.copy2(stored, temporary)
        temporary.replace(local)


def plan_backup(rime_dir: Path, vault: Path, *, machine: str,
                force: bool = False) -> list[Action]:
    """Plan a backup, refusing to overwrite another machine's copy.

    The mirror image of plan_restore's rule, and it is missing here for
    exactly one release too long: restore protects local content from the
    vault, but nothing protected the vault from local content. A machine
    holding an *older* file would push it over a newer one and report
    success -- which is how a June-2025 pristine export came to replace a
    cleaned lexicon that another machine had backed up eleven days later.

    Replacing a file this machine itself last backed up is not a conflict:
    that is the ordinary "I edited my config" case, and requiring --force
    for it would train the reflex that makes --force meaningless.

    `machine` is required rather than defaulting, because the unsafe value
    is the one a caller would omit.
    """
    records = read_manifest(vault)
    actions = []
    for rel in VAULTED_FILES:
        local = safe_join(rime_dir, rel)
        stored = safe_join(vault / FILES_DIR, rel)
        if not local.is_file():
            actions.append(Action(rel, "missing-locally"))
            continue
        if not stored.is_file():
            actions.append(Action(rel, "backup"))
            continue
        if sha256_file(local) == sha256_file(stored):
            actions.append(Action(rel, "identical"))
            continue
        record = records.get(rel)
        if force:
            actions.append(Action(rel, "backup", "forced over the vault's copy"))
        elif record is None:
            # No provenance, so no way to say whose content this replaces.
            actions.append(Action(rel, "conflict",
                                  "the vault's copy is not in the manifest"))
        elif record.machine != machine:
            actions.append(Action(rel, "conflict",
                                  f"the vault's copy came from {record.machine} "
                                  f"at {record.backed_up_at}"))
        else:
            actions.append(Action(rel, "backup"))
    return actions


def apply_backup(rime_dir: Path, vault: Path, actions: Sequence[Action],
                 machine: str, now: str) -> None:
    records = read_manifest(vault)
    for action in actions:
        if action.kind != "backup":
            continue
        local = safe_join(rime_dir, action.rel)
        stored = safe_join(vault / FILES_DIR, action.rel)
        stored.parent.mkdir(parents=True, exist_ok=True)
        temporary = stored.with_name(stored.name + ".new")
        shutil.copy2(local, temporary)
        temporary.replace(stored)
        records[action.rel] = Record(sha256=sha256_file(local),
                                     size=local.stat().st_size,
                                     backed_up_at=now, machine=machine)
    write_manifest(vault, records)
